#!/bin/sh
changed_paths=$(git diff-tree --no-commit-id --name-only -r HEAD)
powershell -NoProfile -ExecutionPolicy Bypass -File "tools/dev/refresh_dist_if_needed.ps1" -Trigger post-merge -ChangedPaths $changed_paths
