name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Lint (ruff: undefined names + syntax)
        run: |
          python -m pip install ruff
          ruff check --select F821,F822,F823,E9 keyquest.pyw modules games ui tests
      - name: Syntax check (compileall)
        run: python -m compileall -q keyquest.pyw modules games ui
      - name: Unit tests (unittest)
        run: |
          mkdir -p tests/logs
          python -m unittest discover -s tests -p "test_*.py" -v | tee tests/logs/unittest.log
      - name: Contrast audit (non-blocking output)
        run: python tools/quality/check_contrast.py
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: tests/logs
