name: Pages
on:
  push:
    branches: [main, work, 'claude/**']
  workflow_dispatch:
permissions: { contents: read, pages: write, id-token: write }
concurrency: { group: "pages", cancel-in-progress: true }
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: app } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm, cache-dependency-path: app/package-lock.json }
      - name: Install
        run: npm ci
      - name: Generate build metadata (public/build.json)
        run: |
          COMMIT=$(git rev-parse --short HEAD || echo local)
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          mkdir -p public
          printf "{\"commit\":\"%s\",\"built\":\"%s\"}\n" "$COMMIT" "$DATE" > public/build.json
          cat public/build.json
      - name: Build (Vite with /keyquest/ base)
        run: npx vite build --base=/keyquest/
      - name: Post-build: copy build.json into dist and verify
        run: |
          cp -f public/build.json dist/build.json || true
          ls -la dist || true
          test -f dist/build.json || (echo "❌ dist/build.json missing" && exit 1)
          cat dist/build.json
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with: { path: app/dist }
  deploy:
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4